In [1]:
import h5py
import numpy as np
import tensorflow.keras as Keras
from sklearn.model_selection import train_test_split

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [3]:
class DataGenerator(Keras.utils.Sequence):

    def __init__(self,dataset,batch_size=5,shuffle=False):

        self.dataset = dataset
        self.batch_size = batch_size
        self.shuffle = shuffle
        self.on_epoch_end()

    def __len__(self):

        return int(np.floor(len(self.dataset)/self.batch_size))

    def __getitem__(self,index):

        indexes = self.indices[index * self.batch_size : (index+1) * self.batch_size]
        feature, label = self.__data_generation(indexes)

        return feature, label

    def __data_generation(self,indexes):

        feature = np.empty((self.batch_size,320,1024))
        label = np.empty((self.batch_size,320,1))

        for i in range(len(indexes)):
            feature[i,] = np.array(self.dataset[indexes[i]][0])
            label[i,] = np.array(self.dataset[indexes[i]][1]).reshape(-1,1)

        return feature,label

    def on_epoch_end(self):

        self.indices = np.arange(len(self.dataset))
        if self.shuffle == True:
            np.random.shuffle(self.indices)

In [4]:
class DatasetMaker(object):

    def __init__(self,data_path):

        self.data_file = h5py.File(data_path)

    def __len__(self):

        return len(self.data_file)

    def __getitem__(self,index):

        index += 1
        video = self.data_file['video_'+str(index)]
        feature = np.array(video['feature'][:])
        label = np.array(video['label'][:])

        return feature,label,index

def get_loader(path, batch_size=5):

    dataset = DatasetMaker(path)
    train_dataset, test_dataset = train_test_split(dataset, test_size = 0.2)
    train_loader = DataGenerator(train_dataset)

    return train_loader, test_dataset

In [5]:
train_loader, test_dataset=get_loader('/content/drive/MyDrive/suvidha internship/fcsn_tvsum.h5')

In [7]:
train_loader.__getitem__(1)

(array([[[0.35250884, 0.35687858, 0.37622839, ..., 0.4116306 ,
          0.37593332, 0.41581485],
         [0.33224654, 0.381078  , 0.34691849, ..., 0.41855153,
          0.40180525, 0.39628667],
         [0.35970178, 0.37046221, 0.35555354, ..., 0.41693273,
          0.40011674, 0.42686591],
         ...,
         [0.37487707, 0.3455686 , 0.3770965 , ..., 0.41539136,
          0.39820242, 0.36128262],
         [0.37143588, 0.35041133, 0.38537401, ..., 0.42188835,
          0.41068125, 0.3635914 ],
         [0.37933877, 0.35179704, 0.38787192, ..., 0.41555437,
          0.40098241, 0.35158965]],
 
        [[0.34310278, 0.32379588, 0.3629739 , ..., 0.41467142,
          0.4268606 , 0.40030608],
         [0.3324433 , 0.34779271, 0.33534241, ..., 0.41157749,
          0.38300651, 0.40324458],
         [0.34330019, 0.34221551, 0.31614497, ..., 0.41342187,
          0.38614759, 0.41145793],
         ...,
         [0.36588389, 0.3762069 , 0.33913556, ..., 0.43120918,
          0.3935608 , 0.

In [9]:
test_dataset[1]

(array([[0.319943  , 0.37948456, 0.32990432, ..., 0.43006426, 0.38723537,
         0.43616933],
        [0.32591122, 0.3689806 , 0.34779176, ..., 0.4292725 , 0.3834775 ,
         0.4353265 ],
        [0.32701132, 0.37345025, 0.344078  , ..., 0.43138295, 0.38321468,
         0.43406087],
        ...,
        [0.3387942 , 0.36302942, 0.3892704 , ..., 0.41417256, 0.38435096,
         0.39531755],
        [0.35451224, 0.35858825, 0.35803077, ..., 0.44103327, 0.41493303,
         0.4012603 ],
        [0.3536804 , 0.3568709 , 0.35599893, ..., 0.44360656, 0.41518053,
         0.3995843 ]], dtype=float32),
 array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 1., 1., 1.,
        1., 0.